### ISSUE TITLE
`load_and_authorize_api_resource` usage of `accessible_by` can not accept blocks

### ISSUE THREAD

**Issue by seattlecyclist** [bullet-train-co/bullet_train-api#11]
w/in `Api::V1::LoadsAndAuthorizesApiResource` this line:
```
        all_accessible_api_resources = api_resource_class.accessible_by(current_ability, permission)

```
will raise the following error when given a  block as a definition.
### Sample CanCanCan ability definition:
```
      can [:create, :read, :destroy, :edit, :update], Orders::LineItem do |line_item|
        true #does not matter
      end
```

### Error:
```
#<CanCan::Error: The accessible_by call cannot be used with a block 'can' definition.The SQL cannot be determined for :read Orders::LineItem
````

**Comment by gazayas** [comment]
@seattlecyclist Since this seems to be the way CanCan is designed to work with `accessible_by`, I'm reluctant to change what we have in `Api::V1::LoadsAndAuthorizesApiResource` (unless @andrewculver wants there to be some kind of workaround so developers don't have to think about it).

The reason I say this is because it's expressed [pretty clearly in the docs](https://github.com/ryanb/cancan/wiki/Defining-Abilities-with-Blocks#fetching-records) that to use `accessible_by` with a `can` block, you need to pass an SQL query along with it to work:
```ruby
can [:create, :read, :destroy, :edit, :update], Orders::LineItem, Orders::LineItem.all do |line_item|
  # Custom processing
end
```

The question would just be if we want to limit developers to using SQL queries in their blocks because we're exclusively using `accessible_by`, or if we should scrap `accessible_by` and change the way we get records in `load_and_authorize_api_resource` altogether.

With that being said, issue #13 was definitely something that needed to be addressed, so I'm glad you brought that up.

1. [Stack Overflow post from a while back](https://stackoverflow.com/questions/3557091/using-blocks-to-define-abilities-in-cancan-raises-an-exception)
2. [Conversation about updating CanCan's docs](https://github.com/ryanb/cancan/issues/276)
